config/routes.rb
Whobuilds::Application.routes.draw do
  devise_for :people, :path_names => { :sign_in => 'login', :sign_out => 'logout' }, :as => "person"
  resource :person
  
  get "token/reset"

  resources :machines
  
  resources :locks do
    member do
      get 'extend'
    end
  end
  post 'locks/quick/:machine_id' => 'locks#create', :as => :quick_locks
  

  root :to => "locks#index"

end

app/models/lock.rb
class Lock < ActiveRecord::Base
  belongs_to :person
  belongs_to :machine

  scope :expired, lambda { where("done_at < ?", Time.zone.now) } do
    def clear
      each { |e| e.destroy }
    end
  end
    
  def extend_time(minutes = 30)
    self.done_at = self.done_at.advance(:minutes => minutes)
  end
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_one :lock, :dependent => :destroy
  
  validates :name, :presence => true, :uniqueness => true
  
  scope :available, joins('LEFT OUTER JOIN locks l ON machines.id = l.machine_id').where(:l => {:id => nil})
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :locks, :dependent => :destroy
  has_many :locked_machines, :through => :locks, :class_name => "Machine", :foreign_key => "machine_id"

  devise :database_authenticatable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :lockable, :timeoutable, :invitable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :invitation_token
  
  validates :name, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  
  after_create :ensure_authentication_token!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_person!
  
  protect_from_forgery
  
  def redirect_with_delay(url, delay = 0)
    @redirect_url, @redirect_delay = url, delay
  end
end

app/controllers/locks_controller.rb
class LocksController < ApplicationController
  inherit_resources
  actions :all, :except => [ :new ]
  
  skip_before_filter :authenticate_person!, :only => [:index]
  before_filter :clear_expired_locks, :only => [:index]

  def index
    redirect_with_delay(root_url, 5)
    index!
  end

  def update
    update! do |success, failure|
      success.html { redirect_to collection_url }
    end
  end
  
  def create
    @lock = Lock.new(params[:lock])
    @lock.machine_id = params[:machine_id] if params[:machine_id]
    @lock.person = current_person
    @lock.done_at = 2.hours.from_now
    begin
      create!(:notice => "It's all yours. Happy building.") { locks_path }
    rescue ActiveRecord::RecordNotUnique
      redirect_to(locks_path)
    end
  end
  
  def extend
    lock = Lock.find(params[:id])
    if lock && lock.machine
      lock.extend_time(30)

      respond_to do |wants|
        if lock.save
          flash[:notice] = "Lock extended 30 minutes."
          wants.html { redirect_to(locks_path) }
          wants.xml  { render :xml => lock, :status => :created, :location => lock }
        else
          wants.html { render :action => "index" }
          wants.xml  { render :xml => lock.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to(locks_path)
    end
  end

  private
  
  # clear expired lock for the current location
  def clear_expired_locks
    Lock.expired.clear
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  inherit_resources
  
  # create a 2 hour lock for current user on given machine
  # def lock
  #   machine = Machine.find(params[:id])
  #   if machine && machine.lock.nil?
  #     lock = machine.build_lock(:person => current_person, :done_at => 2.hours.from_now)
  # 
  #     respond_to do |wants|
  #       if lock.save
  #         flash[:notice] = "It's all yours. Happy building."
  #         wants.html { redirect_to(locks_path) }
  #         wants.xml  { render :xml => lock, :status => :created, :location => lock }
  #       else
  #         wants.html { render :action => "index" }
  #         wants.xml  { render :xml => lock.errors, :status => :unprocessable_entity }
  #       end
  #     end
  #   else
  #     redirect_to(locks_path)
  #   end
  # end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :find_person, :only => [:edit, :update, :destroy]

  # GET /person/edit
  def edit
  end

  # PUT /person
  # PUT /person.xml
  def update
    # if resource.update_with_password(params[resource_name])
    #   set_flash_message :notice, :updated
    #   redirect_to after_update_path_for(resource)
    # else
    #   clean_up_passwords(resource)
    #   render_with_scope :edit
    # end
    
    respond_to do |wants|
      if @person.update_with_password(params[:person])
        flash[:notice] = 'You updated your account successfully.'
        wants.html { redirect_to(after_update_path_for(@person)) }
        wants.xml  { head :ok }
      else
        @person.clean_up_passwords if @person.respond_to?(:clean_up_passwords)
        wants.html { render :action => "edit" }
        wants.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /peoples/1
  # DELETE /peoples/1.xml
  def destroy
    @person.destroy

    respond_to do |wants|
      wants.html { redirect_to(root_url) }
      wants.xml  { head :ok }
    end
  end

  private
    def find_person
      @person = current_person
    end

end

app/controllers/token_controller.rb
class TokenController < ApplicationController

  def reset
    current_person.reset_authentication_token!
    redirect_to :back, :notice => "Authentication token has been reset. Don't forget to update your links."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_heading
    @page_heading || "#{controller_name.humanize} #{action_name.humanize}"
  end
  
  def available_machines_sidebar
    render 'layouts/available_machines_sidebar', :machines => Machine.available unless Machine.available.count.blank?
  end
end

app/helpers/locks_helper.rb
module LocksHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/token_helper.rb
module TokenHelper
end

app/views/layouts/_available_machines_sidebar.html.erb
<div class="box">
  <h2>Available Machines</h2>
  <div class="block" id="available_machines">
    <% machines.each do |machine| %>
      <div class="grid_2 alpha omega">
        <p><%= machine.name %></p>
      </div>
      <div class="grid_2 alpha omega">
        <p><%= link_to "Lock Now", quick_locks_path(machine), :method => :post %></p>
      </div>
      <div class="clear"></div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Who Builds?</title>
    <% if @redirect_url %>
      <meta http-equiv='refresh' content='<%= @redirect_delay -%>;url=<%= @redirect_url -%>'>
    <% end %>
    <%= stylesheet_link_tag('reset', 'text', '960gs', 'layout', 'nav', :media => 'screen, projection') %>
    <!--[if IE 6]><%= stylesheet_link_tag('ie6', :media => 'screen, projection') %><![endif]-->
    <!--[if IE 7]><%= stylesheet_link_tag('ie', :media => 'screen, projection') %><![endif]-->
    <%= stylesheet_link_tag('application', 'formtastic', 'formtastic_changes', :media => 'screen, projection') %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="container_16">
      <div class="grid_16">
        <h1 id="branding">
          <a href="<%= root_url %>">Who Builds?</a>
        </h1>
      </div>
      <div class="clear"></div>
      <div class="grid_16">
        <ul class="nav main">
          <% if person_signed_in? %>
          <li>
            <%= link_to "Home", locks_path %>
          </li>
          <li>
            <%= link_to "Machines", machines_path %>
          </li>
          <li>
            <%= link_to "Add Builder", new_person_invitation_path %>
          </li>
          <li class="secondary">
            <%= link_to "Sign out", destroy_person_session_path %>
          </li>
          <li class="secondary">
            <%= link_to "Account", edit_person_path %>
          </li>
          <% else %>
          <li class="secondary">
            <%= link_to "Sign in", new_person_session_path %>
          </li>
          <% end %>
        </ul>
      </div>
      <div class="clear"></div>
      <div class="grid_16">
        <h2 id="page-heading"><%= page_heading %></h2>
      </div>
      <div class="clear"></div>
      <div class="grid_12">
        <%= yield %>
        <div class="clear"></div>
      </div>
      <div class="grid_4">
        <%= available_machines_sidebar if person_signed_in? %>
        <div class="clear"></div>
        <%= content_for :sidebar %>
      </div>      
      <div class="clear"></div>
      <div class="grid_16" id="site_info">
        <div class="box">
          <p></p>
        </div>
      </div>
      <div class="clear"></div>
    </div>
    <%= javascript_include_tag :defaults, :cache => false %>
  </body>
</html>

app/views/locks/_form.html.erb
<%= semantic_form_for resource do |form| %>
 <%= form.inputs %>
 <%= form.buttons %>
<% end %>

app/views/locks/edit.html.erb
<% @page_heading = "Editing lock" %>

<div class="prefix_1 suffix_1">
  <%= render 'form' %>

  <%= link_to 'Show', @lock %> |
  <%= link_to 'Back', locks_path %>
</div>

app/views/locks/index.html.erb
<% @page_heading = "Locked Machines" %>

<div class="grid_12 center">
  <p id="notice"><%= notice %></p>
</div>
<div class="clear"></div>

<% if @locks.blank? %>
  <div class="grid_12 center">
    <h3>All machines are free.</h3>
  </div>
<% else %>
    <% @locks.each_slice(4) do |locks_slice| %>
      <% locks_slice.each do |lock| %>
        <div class="grid_3 omega">
          <div class="box">
            <h2>
              <%= lock.machine.name %>
            </h2>
            <div class="block">
              <p><strong><%= lock.person.name %></strong> is on this machine for <%= time_ago_in_words(lock.done_at) %></p>
              <div class="center">
                <p><%= link_to '+30', extend_lock_path(lock) %> | <%= link_to 'Edit', edit_lock_path(lock) %> | <%= link_to "Done", lock, :confirm => 'Are you sure you want to relinquish control of this machine?', :method => :delete %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
<% end %>

<div class="clear"></div>

app/views/locks/show.html.erb
<% @page_heading = "Lock" %>

<div class="prefix_1 suffix_1">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Person:</b>
    <%= @lock.person %>
  </p>

  <p>
    <b>Machine:</b>
    <%= @lock.machine %>
  </p>

  <p>
    <b>Done at:</b>
    <%= @lock.done_at %>
  </p>


  <%= link_to 'Edit', edit_lock_path(@lock) %> |
  <%= link_to 'Back', locks_path %>
</div>

app/views/machines/_form.html.erb
<%= semantic_form_for @machine do |form| %>
 <%= form.inputs %>
 <%= form.buttons %>
<% end %>

app/views/machines/edit.html.erb
<% @page_heading = "Editing machine" %>

<div class="prefix_1 suffix_1">
  <%= render 'form' %>

  <%= link_to 'Show', @machine %> |
  <%= link_to 'Back', machines_path %>
</div>

app/views/machines/index.html.erb
<% @page_heading = "Machines" %>

<div class="grid_12 center">
  <p id="notice"><%= notice %></p>
</div>
<div class="clear"></div>

<div class="prefix_1 suffix_1">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @machines.each do |machine| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= machine.name %></td>
          <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
          <td><%= link_to 'Destroy', machine, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br />

  <%= link_to 'New Machine', new_machine_path %>
</div>

app/views/machines/new.html.erb
<% @page_heading = "New machine" %>

<div class="prefix_1 suffix_1">
  <%= render 'form' %>

  <%= link_to 'Back', machines_path %>
</div>

app/views/machines/show.html.erb
<% @page_heading = "Machine" %>

<div class="prefix_1 suffix_1">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Name:</b>
    <%= @machine.name %>
  </p>


  <%= link_to 'Edit', edit_machine_path(@machine) %> |
  <%= link_to 'Back', machines_path %>
</div>

app/views/people/edit.html.erb
<% @page_heading = "Account" %>

<div class="grid_12 center">
  <p id="notice"><%= notice %></p>
</div>
<div class="clear"></div>

<div class="prefix_1 suffix_1">
  <h3>Quick sign in link</h3>
  <p>Drag this link to your bookmarks bar. <%= link_to "Who Builds?", root_path(:auth_token => @person.authentication_token) %></p>
  <p><%= link_to "Reset authentication token", token_reset_path %></p>
  
  <h3>Details</h3>

  <%= semantic_form_for(@person, :url => person_path, :html => { :method => :put }) do |form| %>
    <%= form.inputs do %>
      <%= form.input :name %>
      <%= form.input :email %>
      <%= form.input :password, :hint => "leave blank if you don't want to change it" %>
      <%= form.input :password_confirmation %>
      <%= form.input :current_password, :hint => "we need your current password to confirm your changes" %>    
    <% end %>
    <%= form.buttons do %>
      <%= form.commit_button 'Update' %>
    <% end %>
  <% end %>

  <h3>Cancel my account</h3>

  <p>Unhappy? <%= link_to "Cancel my account", person_path, :confirm => "Are you sure?", :method => :delete %>.</p>

  <%= link_to "Back", :back %>
</div>